version: 2.1

jobs:
  build:
    macos:
      xcode: 11.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set up MacOS
          command: |
            sudo softwareupdate -i -a
            xcode-select --install
            brew update
            brew install yarn